# picogna_photoevaporation_flux_test.yaml

simulation_parameters:
  enable_gas_evolution: true
  test_mode: "photoevap_flux"             # Aktiválja a belső tömegmegmaradási benchmarkot!

disk_parameters:
  # Grid and Disk Initial Parameters (used if no input_file is provided)
  number_of_grid_points: 512    # Corresponds to 'ngrid_val' (-n)
  radial_grid_type: "logarithmic" # "linear" (default) or "logarithmic"
  inner_radius_au: 1.0           # Corresponds to 'rmin_val' (-ri)
  outer_radius_au: 300.0           # Corresponds to 'rmax_val' (-ro)
  initial_gas_sigma0_msun_per_au2: 1e-5
  sigma_profile_exponent: -1    # Corresponds to 'sigmap_exp_val' (-index_init)
  alpha_viscosity: 0.0001          # Corresponds to 'alpha_visc_val' (-alpha_init)
  star_mass_msun: 0.7            # Corresponds to 'star_val' (-m0_init)
  aspect_ratio_at_1au: 0.05      # Corredesponds to 'hasp_val' (-h_init)
  density_floor: 1e-20
  # PHOTOEVAPORATION SELECTION
  # Options: "Owen", "Picogna"
  photoevaporation_mode: "Picogna"
  xray_luminosity_erg_s: 2e30


boundary_conditions:
  inner_boundary_condition: "zero_gradient" # Reference BC_IN == 1
  outer_boundary_condition: "zero_gradient"     # Options: "zero_gradient", "parabolic", "fixed_flux", "absorbing", "reflecting", "linear_extrapolation"

output_parameters:
  # File I/O Parameters
  output_directory_name: "notebooks/photoevaporation_test/photoevaporation_picogna"    # Output directory name (-o)
  

time_parameters:
  # Time Parameters
  total_simulation_time: 1e6       # Corresponds to 'totalTime' (-tmax)
  output_write_frequency: 50000     # Corresponds to 'outputFrequency' (-outfreq)

log_parameters:
  info_level: "info" # "none", "info", or "debug"
  disable_terminal_panels: true